# Generated by Django 4.2 on 2026-01-10 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('original_title', models.CharField(max_length=255, verbose_name='Оригинальное название')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сюжета')),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на постер')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='ID в TMDB API')),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID в IMDb')),
                ('composite_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Средний рейтинг из всех источников (нормализованный к 10-балльной шкале)', max_digits=4, null=True, verbose_name='Композитный рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FilmPersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Актер'), ('director', 'Режиссер'), ('writer', 'Сценарист'), ('producer', 'Продюсер'), ('composer', 'Композитор'), ('cinematographer', 'Оператор'), ('editor', 'Монтажер'), ('other', 'Другое')], max_length=50, verbose_name='Роль в фильме')),
                ('character_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название персонажа')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем важнее роль (для актеров: 0 - главная роль)', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
            ],
            options={
                'verbose_name': 'Роль в фильме',
                'verbose_name_plural': 'Роли в фильмах',
                'ordering': ['film', 'role', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя и фамилия на русском')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя на языке оригинала')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='ID в TMDB API')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фотографию')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('profession', models.CharField(choices=[('actor', 'Актер'), ('director', 'Режиссер'), ('writer', 'Сценарист'), ('producer', 'Продюсер'), ('composer', 'Композитор'), ('cinematographer', 'Оператор'), ('editor', 'Монтажер'), ('other', 'Другое')], default='actor', max_length=50, verbose_name='Основная профессия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('imdb', 'IMDb'), ('rotten_tomatoes', 'Rotten Tomatoes'), ('metacritic', 'Metacritic'), ('kinopoisk', 'Кинопоиск')], max_length=50, verbose_name='Источник')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Значение рейтинга')),
                ('max_value', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Максимальное значение шкалы')),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=2, help_text='Значение рейтинга, приведенное к 10-балльной шкале', max_digits=4, null=True, verbose_name='Нормализованное значение (к 10-балльной шкале)')),
                ('votes_count', models.IntegerField(blank=True, null=True, verbose_name='Количество голосов')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['film', 'source'],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='core_person_name_ab6274_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['tmdb_id'], name='core_person_tmdb_id_4e21bd_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['profession'], name='core_person_profess_0748b7_idx'),
        ),
        migrations.AddField(
            model_name='filmpersonrole',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_roles', to='core.film', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='filmpersonrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='core.person', verbose_name='Персона'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['title'], name='core_film_title_efa29a_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['year'], name='core_film_year_ac4913_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['composite_rating'], name='core_film_composi_654d33_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['tmdb_id'], name='core_film_tmdb_id_61bd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['imdb_id'], name='core_film_imdb_id_1f7c37_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['film', 'source'], name='core_rating_film_id_e8fe88_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['source'], name='core_rating_source_c4e04e_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['normalized_value'], name='core_rating_normali_778dac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('film', 'source')},
        ),
        migrations.AddIndex(
            model_name='filmpersonrole',
            index=models.Index(fields=['film', 'role'], name='core_filmpe_film_id_fa786e_idx'),
        ),
        migrations.AddIndex(
            model_name='filmpersonrole',
            index=models.Index(fields=['person', 'role'], name='core_filmpe_person__e9acb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filmpersonrole',
            unique_together={('film', 'person', 'role')},
        ),
    ]
