# Generated by Django 4.2 on 2026-01-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID в IMDb'),
        ),
    ]
